In [10]:
import imageio as img
import numpy as np

pic = img.imread('../images/Icosahedron.png')
print(pic.shape)
#print(pic)
np.save('picarray', pic)

#to compress the data into simply a 2-dimensional array, we take the RGB values for each pixel and
#compile them as follows: R G B -> R * 256^2 + G * 256 + B = RGB
#thus we obtain a single value that uniquely represents every colour in the 8-bit RGB gamut
#conversion back would be a simple matter of RGB -> RGB//256^2 = R, RGB%256//256 = G, RGB%256 = B
pWidth = pic.shape[0]
pHeight = pic.shape[1]
print(pWidth, pHeight)
compressedPic = np.zeros((pWidth, pHeight))
intermediatePic = np.zeros((pWidth, pHeight))
multiplyArray = [256**2, 256, 1]


# intermediatePic = np.multiply(pic, multiplyArray)
# compressedPic = np.sum(intermediatePic, axis=2)

#compressedPic is now a 2-d array with each value representing the colour
#the pixel position is implicit
#our input needs to be m data points in R^n, where n is the number of dimensions (potentially low?)
#could we have n=5 x, y, r, g, b?

compressedPic = np.zeros((pWidth*pHeight, 3))
print(compressedPic)

alterPic = np.reshape(pic, (pWidth*pHeight, 3))
intermediateAlter = np.multiply(alterPic, multiplyArray)
compressedAlter = np.sum(intermediateAlter, axis = 1)

print(compressedAlter[245])


for k in range(pWidth*pHeight):
    compressedPic[k] = [k//pWidth, k%pWidth, compressedAlter[k]]

print(compressedPic)

#compressedPic is now a pq x 3 dimension array where p and q are the width and height of the image
#and the 3rd dimension is a value representing the colour of the represented pixel
#so each data-point has an x value, a y value, and an RGB value (each colour has a unique associated number)
        
np.save('compressedPicArray', compressedPic)

(785, 718, 3)
785 718
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
16777215.0
[[0.0000000e+00 0.0000000e+00 1.6777215e+07]
 [0.0000000e+00 1.0000000e+00 1.6777215e+07]
 [0.0000000e+00 2.0000000e+00 1.6777215e+07]
 ...
 [7.1700000e+02 7.8200000e+02 1.6777215e+07]
 [7.1700000e+02 7.8300000e+02 1.6777215e+07]
 [7.1700000e+02 7.8400000e+02 1.6777215e+07]]


In [16]:
def produceCircle(points, intercept):
    xArr = np.linspace(intercept, -1*intercept, points)
    yArr = [np.sqrt(intercept**2 - x**2) for x in xArr]
    circlePoints = []
    for p in range(points):
        x = xArr[p]
        y = yArr[p]
        circlePoints.append((x, y))
        circlePoints.append((x, -y))
    return circlePoints
    
cir = produceCircle(21, 1)
np.save('circleArray', cir)